version: '3'

services:
  gastarme:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8001"
    ports: 
       - "8001:8001"
    depends_on:
       - db
    volumes:
      - .:/code
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ihopeigetin=)
    
