version: 2
jobs:
  build:
    working_directory: ~/gastarme
    docker:
      - image: circleci/python:3.6.5
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ihopeigetin=)
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd gastarme
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd gastarme
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
