version: 2
jobs:
  build:
    working_directory: ~/gastarme/gastarme
    docker:
      - image: circleci/python:3.6.4
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: ihopeigetin=)
    steps:
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            python manage.py test
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-reports
          destination: test-reports
