site_name: Gastar.me
nav:
    - Home: index.md
    - Roadmap: roadmap.md
    - API Documentation:
      - Users: users.md
      - Authentication: auth.md
      - Superusers: superusers.md
      - Wallets: wallets.md
      - Credit Cards: creditcards.md
      - Purchases: purchases.md
      - Billings: billings.md
theme: readthedocs

